### ISSUE TITLE
Add more 'end of game' stats

### ISSUE THREAD

**Issue by ajschwieterman** [kevinkey/klank#33]
number of monsters killed
number of damage done
number of caves visited
number of distance moved

**Comment by Pachelbel1414** [comment]
maybe some stats on your deck:  # explorer, # merc, # tomes, # dungeon

**Comment by Pachelbel1414** [comment]
in addition to Aaron's dmg done, maybe also dmg taken, dmg healed

**Comment by ajschwieterman** [comment]
number of times healed

**Comment by ajschwieterman** [comment]
number of rooms travelled to
number of cards played

**Comment by ajschwieterman** [comment]
number of coins collected
number of clank removed

**Comment by ajschwieterman** [comment]
number of major and minor secrets collected
