### ISSUE TITLE
problem with Sorcerer

### ISSUE THREAD

**Issue by holtrop** [kevinkey/klank#85]
There was one tome left when I killed the sorcerer. The output shows:

Holtrop gained +0 Tome(s)! There are 0 Tome(s) left!
Holtrop killed Sorcerer in the dungeon!

But it did give me the tome.

**Comment by ajschwieterman** [comment]
Looks like the game gives the tome to the player but then outputs the incorrect amount of tomes left.
https://github.com/kevinkey/klank/blob/d75ce170c0b94799dee37a7c1789c729b9825c00/card.rb#L609-L612

**Comment by holtrop** [comment]
Ah... maybe you need to query @game.reserve[:t].remaining before calling player.tome()?
